import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

import MouseGlow from "./components/MouseGlow";

export const metadata: Metadata = {
  title: "DevBygavin",
  icons: {
    icon: "/logo_with_blackbg.png",
    shortcut: "/logo_with_blackbg.png",
    apple: "/logo_with_blackbg.png",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <MouseGlow />
        {children}
      </body>
    </html>
  );
}
